# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 11:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, null=True, upload_to='media')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sale_rent', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=10)),
                ('house_type', models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT_FLAT', 'Apartment/Flat'), ('TOWNHOUSE', 'Town House'), ('DUPLEX', 'Duplex')], max_length=20)),
                ('beds', models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7')])),
                ('baths', models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7')])),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Residential Real Estate',
            },
        ),
    ]
