# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
