# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_auto_20161201_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='beds',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
    ]
